# Use root/example as user/password credentials
version: '3.1'

services:
  springapp:
    networks:
      - app-network
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:8080
      - 80:80
      - 433:433
    environment:
      psqlHost: $psqlHost
      psqlPort: $psqlPort
      psqlDB: $postgresDb
      psqlUsername: $postgresUser
      psqlPassword: $postgresPassword
    depends_on:
      postgres:
        condition: service_started
  postgres:
    networks:
      - app-network
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $postgresUser
      POSTGRES_PASSWORD: $postgresPassword
      POSTGRES_DB: $postgresDb
networks:
  app-network:
    driver: bridge