# Use root/example as user/password credentials
version: '3.1'

services:
  springapp:
    networks:
      - app-network
    profiles:
      - prod
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:8080
      - 80:80
      - 433:433
    environment:
      psqlHost: $psqlHost
      psqlPort: $psqlPort
      psqlDB: $postgresDb
      psqlUsername: $postgresUser
      psqlPassword: $postgresPassword
    depends_on:
      postgres:
        condition: service_started
  postgres:
    profiles:
      - prod
      - debug
    networks:
      - app-network
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $postgresUser
      POSTGRES_PASSWORD: $postgresPassword
      POSTGRES_DB: $postgresDb
  pgadmin:
    profiles:
      - debug
    networks:
      - app-network
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 256in4@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8090:80
networks:
  app-network:
    driver: bridge